p8105_hw2_ys3765
================
Yixiao Sun
2023-09-30

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readxl)
library(dplyr)
library(readr)
```

\#Problem 2

``` r
mr_trash_wheel <- read_excel("202309 Trash Wheel Collection Data.xlsx",sheet = 1) %>%                       janitor::clean_names() %>% select(-x15,-x16) %>% 
                  mutate(year = as.character(year)) %>%                                                     mutate(month = as.character(month))
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
mr_trash_wheel<- na.omit(mr_trash_wheel)
mr_trash_wheel$homes_powered <- mr_trash_wheel$weight_tons*500/30
mr_trash_wheel
```

    ## # A tibble: 584 × 14
    ##    dumpster month year  date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <chr> <dttm>                    <dbl>              <dbl>
    ##  1        1 May   2014  2014-05-16 00:00:00        4.31                 18
    ##  2        2 May   2014  2014-05-16 00:00:00        2.74                 13
    ##  3        3 May   2014  2014-05-16 00:00:00        3.45                 15
    ##  4        4 May   2014  2014-05-17 00:00:00        3.1                  15
    ##  5        5 May   2014  2014-05-17 00:00:00        4.06                 18
    ##  6        6 May   2014  2014-05-20 00:00:00        2.71                 13
    ##  7        7 May   2014  2014-05-21 00:00:00        1.91                  8
    ##  8        8 May   2014  2014-05-28 00:00:00        3.7                  16
    ##  9        9 June  2014  2014-06-05 00:00:00        2.52                 14
    ## 10       10 June  2014  2014-06-11 00:00:00        3.76                 18
    ## # ℹ 574 more rows
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <dbl>, homes_powered <dbl>

``` r
prof_trash_wheel <- read_excel("202309 Trash Wheel Collection Data.xlsx",sheet = 2) %>%
                    janitor::clean_names()%>%
                    mutate(year = as.character(year)) %>% 
                    mutate(month = as.character(month))
prof_trash_wheel<-prof_trash_wheel[-107,]
prof_trash_wheel$homes_powered <- prof_trash_wheel$weight_tons*500/30
prof_trash_wheel
```

    ## # A tibble: 106 × 13
    ##    dumpster month    year  date                weight_tons volume_cubic_yards
    ##       <dbl> <chr>    <chr> <dttm>                    <dbl>              <dbl>
    ##  1        1 January  2017  2017-01-02 00:00:00        1.79                 15
    ##  2        2 January  2017  2017-01-30 00:00:00        1.58                 15
    ##  3        3 February 2017  2017-02-26 00:00:00        2.32                 18
    ##  4        4 February 2017  2017-02-26 00:00:00        3.72                 15
    ##  5        5 February 2017  2017-02-28 00:00:00        1.45                 15
    ##  6        6 March    2017  2017-03-30 00:00:00        1.71                 15
    ##  7        7 April    2017  2017-04-01 00:00:00        1.82                 15
    ##  8        8 April    2017  2017-04-20 00:00:00        2.37                 15
    ##  9        9 May      2017  2017-05-10 00:00:00        2.64                 15
    ## 10       10 May      2017  2017-05-26 00:00:00        2.78                 15
    ## # ℹ 96 more rows
    ## # ℹ 7 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, homes_powered <dbl>

``` r
gwynnda <- read_excel("202309 Trash Wheel Collection Data.xlsx",sheet = 4) %>%
          janitor::clean_names()%>%mutate(year = as.character(year)) %>% 
          mutate(month = as.character(month))

gwynnda<-gwynnda[-107,]
gwynnda<-gwynnda[-107,]
gwynnda$homes_powered <- gwynnda$weight_tons*500/30
gwynnda
```

    ## # A tibble: 155 × 12
    ##    dumpster month  year  date                weight_tons volume_cubic_yards
    ##       <dbl> <chr>  <chr> <dttm>                    <dbl>              <dbl>
    ##  1        1 July   2021  2021-07-03 00:00:00        0.93                 15
    ##  2        2 July   2021  2021-07-07 00:00:00        2.26                 15
    ##  3        3 July   2021  2021-07-07 00:00:00        1.62                 15
    ##  4        4 July   2021  2021-07-16 00:00:00        1.76                 15
    ##  5        5 July   2021  2021-07-30 00:00:00        1.53                 15
    ##  6        6 August 2021  2021-08-11 00:00:00        2.06                 15
    ##  7        7 August 2021  2021-08-14 00:00:00        1.9                  15
    ##  8        8 August 2021  2021-08-16 00:00:00        2.16                 15
    ##  9        9 August 2021  2021-08-16 00:00:00        2.6                  15
    ## 10       10 August 2021  2021-08-17 00:00:00        3.21                 15
    ## # ℹ 145 more rows
    ## # ℹ 6 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   homes_powered <dbl>

``` r
mr_trash_wheel$trash_wheel <- "Mr. Trash Wheel"
prof_trash_wheel$trash_wheel <- "Professor Trash Wheel"
gwynnda$trash_wheel <- "Gwynnda"
```

``` r
combined_data_step1 <- bind_rows(mr_trash_wheel, prof_trash_wheel)
combined_data<-bind_rows(combined_data_step1,gwynnda)
combined_data
```

    ## # A tibble: 845 × 15
    ##    dumpster month year  date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <chr> <dttm>                    <dbl>              <dbl>
    ##  1        1 May   2014  2014-05-16 00:00:00        4.31                 18
    ##  2        2 May   2014  2014-05-16 00:00:00        2.74                 13
    ##  3        3 May   2014  2014-05-16 00:00:00        3.45                 15
    ##  4        4 May   2014  2014-05-17 00:00:00        3.1                  15
    ##  5        5 May   2014  2014-05-17 00:00:00        4.06                 18
    ##  6        6 May   2014  2014-05-20 00:00:00        2.71                 13
    ##  7        7 May   2014  2014-05-21 00:00:00        1.91                  8
    ##  8        8 May   2014  2014-05-28 00:00:00        3.7                  16
    ##  9        9 June  2014  2014-06-05 00:00:00        2.52                 14
    ## 10       10 June  2014  2014-06-11 00:00:00        3.76                 18
    ## # ℹ 835 more rows
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <dbl>, homes_powered <dbl>, trash_wheel <chr>

For these three dataset, the mr_trash_wheel dataset has 584 rows and 15
after cleaning. The prof_trash_wheel dataset has 106 rows and 14 after
cleaning. The Gwynnda dataset has 155 rows and 13 after cleaning. The
combined dataset has intotal 845 and 15. The important variables in each
of these datasets including the geographic info of the dumpster, but in
order to calculate the trash that could be using for powering homes,
weight_tons variable is the most essential one. The total weight of
trash collected by Professor Trash Wheel dataset is 216.26. And for the
total number of cigarette butts collected by Gwynnda in July of 2021,
the number is 1.63^{4}.

\#Problem 3

``` r
library(readr)
mci_baseline_original <- read_csv("data_mci/MCI_baseline.csv",skip=1)%>%
                janitor::clean_names()
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
mci_baseline <- read_csv("data_mci/MCI_baseline.csv",skip=1)%>%
                janitor::clean_names() %>% 
                mutate(sex = ifelse(sex == 1,"Male","Female")) %>% 
                mutate(apoe4 = ifelse(apoe4 == 1, "Carrier","Non-Carrier")) %>%        
                filter(current_age < age_at_onset|age_at_onset==".")%>%
                mutate(age_at_onset = if_else(age_at_onset == ".", NA, age_at_onset))
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
mci_baseline
```

    ## # A tibble: 479 × 6
    ##       id current_age sex    education apoe4       age_at_onset
    ##    <dbl>       <dbl> <chr>      <dbl> <chr>       <chr>       
    ##  1     1        63.1 Female        16 Carrier     <NA>        
    ##  2     2        65.6 Female        20 Carrier     <NA>        
    ##  3     3        62.5 Male          16 Carrier     66.8        
    ##  4     4        69.8 Female        16 Non-Carrier <NA>        
    ##  5     5        66   Male          16 Non-Carrier 68.7        
    ##  6     6        62.5 Male          16 Non-Carrier <NA>        
    ##  7     7        66.5 Male          18 Non-Carrier 74          
    ##  8     8        67.2 Female        18 Non-Carrier <NA>        
    ##  9     9        66.7 Female        16 Non-Carrier <NA>        
    ## 10    10        64.1 Female        18 Non-Carrier <NA>        
    ## # ℹ 469 more rows

``` r
mci_amyloid <- read_csv("data_mci/mci_amyloid.csv",skip = 1)%>%
              janitor::clean_names()%>%
              rename("id" = "study_id")%>%
              pivot_longer(baseline:time_8,
                           names_to = "year",
                           values_to = "value" )%>%
              mutate(year =  case_match(
                              year,
                            "baseline" ~ 0, 
                            "time_2" ~ 2, 
                            "time_4" ~ 4,
                            "time_6" ~ 6, 
                            "time_8" ~ 8))
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (5): Baseline, Time 2, Time 4, Time 6, Time 8
    ## dbl (1): Study ID
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
mci_amyloid
```

    ## # A tibble: 2,435 × 3
    ##       id  year value      
    ##    <dbl> <dbl> <chr>      
    ##  1     1     0 0.1105487  
    ##  2     1     2 <NA>       
    ##  3     1     4 0.109325197
    ##  4     1     6 0.104756131
    ##  5     1     8 0.107257697
    ##  6     2     0 0.107481183
    ##  7     2     2 0.109157373
    ##  8     2     4 0.109457839
    ##  9     2     6 0.105729713
    ## 10     2     8 0.10661845 
    ## # ℹ 2,425 more rows

``` r
only_data<-anti_join(mci_baseline,mci_amyloid)
```

    ## Joining with `by = join_by(id)`

``` r
only_data_2<-anti_join(mci_amyloid,mci_baseline)
```

    ## Joining with `by = join_by(id)`

``` r
only_data
```

    ## # A tibble: 8 × 6
    ##      id current_age sex    education apoe4       age_at_onset
    ##   <dbl>       <dbl> <chr>      <dbl> <chr>       <chr>       
    ## 1    14        58.4 Female        20 Non-Carrier 66.2        
    ## 2    49        64.7 Male          16 Non-Carrier 68.4        
    ## 3    92        68.6 Female        20 Non-Carrier <NA>        
    ## 4   179        68.1 Male          16 Non-Carrier <NA>        
    ## 5   268        61.4 Female        18 Carrier     67.5        
    ## 6   304        63.8 Female        16 Non-Carrier <NA>        
    ## 7   389        59.3 Female        16 Non-Carrier <NA>        
    ## 8   412        67   Male          16 Carrier     <NA>

``` r
only_data_2
```

    ## # A tibble: 80 × 3
    ##       id  year value      
    ##    <dbl> <dbl> <chr>      
    ##  1    72     0 0.106965463
    ##  2    72     2 <NA>       
    ##  3    72     4 0.107266218
    ##  4    72     6 0.106665207
    ##  5    72     8 <NA>       
    ##  6   234     0 0.110521689
    ##  7   234     2 0.110988335
    ##  8   234     4 0.110318671
    ##  9   234     6 0.107334344
    ## 10   234     8 0.108868811
    ## # ℹ 70 more rows

``` r
Combined_data_2<-inner_join(mci_baseline,mci_amyloid)
```

    ## Joining with `by = join_by(id)`

``` r
Combined_data_2
```

    ## # A tibble: 2,355 × 8
    ##       id current_age sex    education apoe4   age_at_onset  year value      
    ##    <dbl>       <dbl> <chr>      <dbl> <chr>   <chr>        <dbl> <chr>      
    ##  1     1        63.1 Female        16 Carrier <NA>             0 0.1105487  
    ##  2     1        63.1 Female        16 Carrier <NA>             2 <NA>       
    ##  3     1        63.1 Female        16 Carrier <NA>             4 0.109325197
    ##  4     1        63.1 Female        16 Carrier <NA>             6 0.104756131
    ##  5     1        63.1 Female        16 Carrier <NA>             8 0.107257697
    ##  6     2        65.6 Female        20 Carrier <NA>             0 0.107481183
    ##  7     2        65.6 Female        20 Carrier <NA>             2 0.109157373
    ##  8     2        65.6 Female        20 Carrier <NA>             4 0.109457839
    ##  9     2        65.6 Female        20 Carrier <NA>             6 0.105729713
    ## 10     2        65.6 Female        20 Carrier <NA>             8 0.10661845 
    ## # ℹ 2,345 more rows

``` r
write_csv(Combined_data_2,"/Users/elliot-sun/Desktop/P8105_ Data Science/p8105_hw2_ys3765/data_mci/combined_data.csv")
```

For the cleaning process, I first change the the second dataset’s
`study_id` into `id` in order to better combine the two datasets, then I
change the `sex` and `apoe4` columns in the first dataset from character
into numeric. Then to better clean the amyloid dataset, I chose
pivot_longer function and renamed the columns of the dataset to utlize
better with all the information. Anti_join function was used for finding
the number of people who only appeared once in each dataset. And finally
I used inner_join function to fully combined these two datasets.

For these two datasets, the first cleaning step is to find those
patients who do not show MCI at baseline. The baseline dataset showing
features of the patients’ geographical info including educational level,
age, the onset age. So the basic cleaning step should be using the
current age to compare with the age at onset, and we get 479 rows of the
dataset, comparing with the original dataset has 483 numbers of
participants recrutied. The average baseline age is 65.0286013. The
proportion of women in the study are APOE4 carriers are 30%.

For the two datasets, the mci_baseline has 479 rows before cleaning, and
for the mci_amyloid has 2435 rows. So partial participants appeared in
only one dataset.(8 and 80 from the function only_data and only_data_2).
The combined dataset cleaned the data and put the same patients’ value
together in the order of time length(from beginning to 8 years), the
whole dataset contains 2355 all other demographic info are shown alone
with the age and ID and values.
